sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1687380525lyb
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: vBtEIBfpEmgaa69v8YqqWsHdbgm88V
    access-key-id: LTAI5t6E33g8UtkDydRCmVN1
    bucket-name: web-ligejiuye
